### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by pennomi** [silveira/openpixels#9]
You mention that your art here is "open source" but don't give a specific license. Could you add a LICENSE file to your repo so we know what terms we're under to use these assets?

I'd recommend one of the Creative Commons licenses, in particular CC-BY.

**Comment by osuka** [comment]
so... how about adding that LICENSE.txt file? how about this: https://creativecommons.org/licenses/by-sa/4.0/

A simple document with the specific type of license and the link should suffice.

**Comment by silveira** [comment]
thanks @pennomi @sombriks @osuka for the feedback. I hope with the LICENSE file we have less confusion about what can or cannot be done with the assets of openpixels.
